### PR TITLE
added nodemon to package.json

### PR DESCRIPTION
**Pull request by saravanan-coder**
nodemon is a command line interface that can be used for  restarting the server

### CODE REVIEW

**Comment by wagnerand** [comment]
What problem does adding this dependency solve?

**Comment by saravanan-coder** [comment]
> What problem does adding this dependency solve?

Adding this can run server without restarting it

**Comment by wagnerand** [comment]
Can you explain in more details what exact problem you are having and how this PR solves it? Thanks!

**Comment by saravanan-coder** [comment]
It is not a problem by adding this nodemon in server side packages it can automatically restart the application when file changes are detected

**Pull request closed without merging**
